# fly.toml app configuration file generated for bodomow-fullstackopen-part3 on 2024-05-22T11:19:15-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bodomow-fullstackopen-part3'
primary_region = 'qro'

[build]

[env]
  PORT = "3000" # add this

[http_service]
  internal_port = 3000 # ensure that this is same as PORT
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
